version: "2"
services:
  web:
    image:  nginx:1.13 
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/
      - ./conf/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    image: hellosanta/php4drupal:php7.0-fpm
    volumes:
      - ./www:/var/www/html/
    restart: always
    links:
      - db
  db:
    image: mysql:5.7.18
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=todo
      - MYSQL_ROOT_PASSWORD=todo